//
// Created by ACER on 25/10/2025.
//

#ifndef INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_TORNEO_H
#define INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_TORNEO_H


class Torneo {
};


#endif //INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_TORNEO_H