//
// Created by ACER on 25/10/2025.
//

#ifndef INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_VIDEOJUEGO_H
#define INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_VIDEOJUEGO_H


class Videojuego {
};


#endif //INC_8_PRACTICA_MAPA_VECTOR_MANUELR0107_VIDEOJUEGO_H